services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cloud_db
      POSTGRES_USER: ivana_teste
      POSTGRES_PASSWORD: senha12345
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack:3.0
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"

  storage-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - localstack